### ISSUE TITLE
Feature request: affinity support

### ISSUE THREAD

**Issue by cyrilcros** [nextcloud/helm#118]
Please add a value for setting the `affinity` of nextcloud pods, maybe a separate one for the metrics...

**Comment by cyrilcros** [comment]
Well, affinity can be set but this is missing from the `values.yaml`

**Comment by hyacin75** [comment]
> Well, affinity can be set but this is missing from the `values.yaml`

How?  :-/

**Comment by provokateurin** [comment]
@hyacin75 We welcome every PR. We have a big backlog of old PRs but we try to merge everything that makes sense
