### ISSUE TITLE
batch/v1beta1 CronJob is deprecated in v1.21+

### ISSUE THREAD

**Issue by mrtndwrd** [nextcloud/helm#157]
The CronJob has moved from batch/v1beta1 to batch/v1. I get these warnings when I install the Nextcloud chart (version `2.9.0`) with `cronjob.enabled` set to `true`.

```
W1027 16:42:29.067238   58078 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
W1027 16:42:31.810061   58078 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
W1027 16:42:31.881846   58078 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
```

**Comment by jgallucci32** [comment]
This was sort of fixed in https://github.com/nextcloud/helm/commit/f53dbf884e71b23cc3241a042cd456d59ca0d9a3 but this commit introduced a regression in that in v1.20 of kubernetes you get the following error
```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "CronJob" in version "batch/v1"
```

**Comment by provokateurin** [comment]
The cronjob is now using the NC cronjob instead of the k8s cronjob, so this is not relevant anymore.
