### ISSUE TITLE
Nextcloud pods working, nexctcloud asking to be reistalled

### ISSUE THREAD

**Issue by urbaman** [nextcloud/helm#261]
Hi,

I finally found a way to start nextcloud with the helm chart, but it's asking me to be reinstalled (sorry for the italian):

"Sembra che tu stia tentando di reinstallare il tuo Nextcloud. Tuttavia, manca il file CAN_INSTALL dalla cartella config. Crea il file CAN_INSTALL nella cartella config per continuare."

But I should have all of this done with the chart, isn't it?

Here's my config-php:

```
<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'overwriteprotocol' => 'https',
  'overwrite.cli.url' => 'https://nextcloud.example.com',
  'filelocking.enabled' => 'true',
  'loglevel' => '2',
  'enable_previews' => true,
  'trusted_domains' =>
  array (
    0 => 'nextcloud',
    1 => 'nextcloud.example.com',
  ),
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'nextcloud-redis-master',
    'port' => '6379',
    'password' => 'nextcloud-admin',
  ),
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'smtp.example.com',
  'mail_smtpport' => '587',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauth' => true,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpname' => 'nextcloud@example.com',
  'mail_smtppassword' => 'password',
  'mail_from_address' => 'nextcloud',
  'mail_domain' => 'example.com',
  'passwordsalt' => 'passwordsalt',
  'secret' => 'secret',
  'datadirectory' => '/var/www/html/data',
  'dbtype' => 'mysql',
  'version' => '24.0.2.1',
  'dbname' => 'nextcloud',
  'dbhost' => 'nextcloud-mariadb',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'dbuser',
  'dbpassword' => 'dbpassword',
  'instanceid' => 'instanceid',
);
```

**Comment by urbaman** [comment]
Also: if I go on creating the CAN_CONFIG file, and trying to setup the config, the form isn't respondig, like when I try to choose the db, it's not responding.

**Comment by StephenLasseter** [comment]
If the helm chart is working for you, you would not be presented with an install screen, but just a login screen.  If I'm guessing correctly, I but you are being asked to create an admin account and then presented with db connection options that don't work?

Can you post your values file?  And can you confirm you are starting with no tables populated (if so you would need to drop them assuming you don't need that data).

Output of a describe on the nextcloud deployment and pod as well as mariadb deployment and pod would also be helpful.
