### ISSUE TITLE
cronjob has no tag

### ISSUE THREAD

**Issue by MichaelSp** [nextcloud/helm#263]
With this configuration:

```yaml
 cronjob:
      enabled: true
```

The following (incorrect) image will be generated: `image: 'nextcloud:'`

**Comment by mrtndwrd** [comment]
Probably introduced with this commit: https://github.com/nextcloud/helm/commit/6197310517f8ecfe322d24989eb8efa84ea83e61

This affects everyone that uses the cronjobs.

**Comment by mrtndwrd** [comment]
I'll make a PR

**Comment by mrtndwrd** [comment]
Workaround: [set `cronjob.image.repository` and `cronjob.image.tag`](https://github.com/nextcloud/helm/blob/master/charts/nextcloud/values.yaml#L299)
