### ISSUE TITLE
Release chart version: 3.1.0

### ISSUE THREAD

**Issue by Nerkho** [nextcloud/helm#270]
Currently, the available chart in the repo is still version 3.0.4 despite the version bump introduced by #267
Can you release chart version 3.1.0 ? 

```
~ ❯ helm search repo nextcloud                                                                                                                                           
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
nextcloud/nextcloud     3.0.4           24.0.2          A file sharing server that puts the control and...
```

**Comment by tvories** [comment]
@Nerkho  thanks for bringing that to my attention.  I didn't see that the workflow failed.  It should be available now.
