### ISSUE TITLE
Database: use existing secrets as credentials

### ISSUE THREAD

**Issue by thetredev** [nextcloud/helm#288]
I can't find a way to define existing secrets for database credentials. The chart template `db-secret.yaml` encrypts the credentials itself if we define them in `values.yaml`.

I'd like to have the ability to choose existing secrets for that and not have them defined as clear text in my `values.yaml`. I could create a PR for that if you'd like.

**Comment by StephenLasseter** [comment]
The database values are passed to the respective bitnami db chart (mariadb or postgress), so you should be able to look at the values.yaml for whichever you are using.  For instance, for mariadb: https://github.com/bitnami/charts/blob/master/bitnami/mariadb/values.yaml

**Comment by thetredev** [comment]
Gotcha, thanks! Issue can be closed.

**Comment by thetredev** [comment]
I'm closing it. :)
