### ISSUE TITLE
.Values.cronjob.enabled is not respected in 3.2.0

### ISSUE THREAD

**Issue by tarhann** [nextcloud/helm#297]
https://github.com/nextcloud/helm/blob/5cbbdf193e2fe2a9f17bfdeb26cf5ef2fd1f676b/charts/nextcloud/templates/deployment.yaml#L128
is not using the `cronjob.enabled` value so that a cronjob is always deployed. If this behavior is intended, sorry for the fuss :)

**Comment by kretzlaff** [comment]
This behavior was not intended. I'll provide a PR that fixes this issue asap.
