### ISSUE TITLE
With cronjob enabled, the Chart does not install

### ISSUE THREAD

**Issue by sseneca** [nextcloud/helm#31]
From the `values.yaml`, "Nexcloud image is used as default but only curl is needed". I chose `curlimages/curl`, but this doesn't work.

With the following:

```
    cronjob:
      enabled: true
      image:
        repository: curlimages/curl
        tag: 7.73.0
```

The `nextcloud-cron` pods fail to get in the `READY` state. The logs:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 503 
```

The main nextcloud pod waits for these, which eventually times out and the installation fails.

Edit: Never mind, the chart is broken even using the default nextcloud image. Deploy file can be found [here](https://gitlab.com/sseneca/k8s-server/-/blob/3983c7d1fa2d2bdea6f14a95d32040ffedc71352/nextcloud/release.yaml#L74).

It looks related to #16. The change broke it for somebody else too:

https://github.com/nextcloud/helm/issues/16#issuecomment-699476764

The error message is different (503 vs 400). Total guess: it's running curl and expecting to find the Nextcloud instance up, but Nextcloud won't be up until after the `cron` pod itself is up.

**Comment by hyperbolic2346** [comment]
Thanks for helping me figure out what was going on here.

**Comment by pfuhrmann** [comment]
Yes. CronJob will fail initially until nextcloud pod itself is running. This actually makes sense to me, not sure if there is anything to fix here.

Once the pod with nextcloud app is running, cronjobs will execute as expected.
