### ISSUE TITLE
Maintenance mode after upgrade

### ISSUE THREAD

**Issue by HerHde** [nextcloud/helm#325]
Greetings,

after upgrading the Helm chart from 3.3.3 to 3.3.4 the maintenance mode is activated. The status.php:

```json
{
  "installed": true,
  "maintenance": true,
  "needsDbUpgrade": true,
  "version": "25.0.2.3",
  "versionstring": "25.0.2",
  "edition": "",
  "productname": "Nextcloud",
  "extendedSupport": false
}
```

Did I miss something? I can't find any upgrade instructions and I don't believe my NC with only a few files needs more than 10 minutes to upgrade the DB automatically. Has anyone else encountered the problem?

**Comment by provokateurin** [comment]
I think you can just disable the maintenance mode via occ. Maintenance mode doesn't mean it's doing any upgrades, it's just a protection.

**Comment by HerHde** [comment]
I assumed it needs a DB upgrade because `needsDbUpgrade` is true. Might that be a false positive?
-- 
Henrik "HerHde" Hüttemann

**Comment by provokateurin** [comment]
Ah hm I didn't see that. Can you run `occ upgrade`?

**Comment by HerHde** [comment]
I tried to find out how to run occ and run the steps necessary. Here's approximately what I did:
```bash
apt update
apt install sudo
sudo -u www-data php occ maintenance:mode --off # I don't think this is necessary before the update, just to test. But afterwards, the web UI told me to upgrade.
sudo -u www-data php occ upgrade
```

Then, after a bit of cache invalidation, it worked.

---

I see a few possible improvements here.

- Updating the docs or README how to run `occ` (#221)
- Adding also the specific upgrade procedure
- Add this as an automation to the Chart functionality

While I can do the first two things on my own (if you tell me these steps are appropriate), I'm not too experienced with creating Helm Charts. But would it be wise to trigger this

- if an upgrade is needed (and how to check this best)
- as a sidecar or init container?

Thanks so far!

**Comment by provokateurin** [comment]
Normally the upgrade just works. I never had any issues with that and just recently upgraded the chart from 3.3.3 to 3.3.4. I think it was just a one time problem.

**Comment by HerHde** [comment]
Hmm, maybe I interrupted the upgrade by deleting the pod. Is there an upgrade flag that might have been set?

**Comment by provokateurin** [comment]
Yeah that could very well be. What kind of flag do you mean?

**Comment by HerHde** [comment]
A flag which defines that the update was started or executed. Which is then checked to determine if an update procedure needs to run. Just my imagination :D
