### ISSUE TITLE
Connect to external postgres database with different port

### ISSUE THREAD

**Issue by tim-kilian** [nextcloud/helm#36]
Usually postgres uses 5432, but in my case it is different. I would need to be able to change the port of the postgres database.

**Comment by chrisingenhaag** [comment]
Hey,
did you try setting `externalDatabase.host: yourhost:5432`? And I assume that you use `externalDatabase: true`.

**Comment by tim-kilian** [comment]
Yes, thanks. Seems to work fine. Sorry for the missing information and my knowledge. Maybe extending the documentation would help.
