### ISSUE TITLE
Can't upgrade Nextcloud from chart version 4.5.3 to 4.5.5

### ISSUE THREAD

**Issue by supermario18b** [nextcloud/helm#493]
Hi everyone,

I can't upgrade nextcloud from chart version 4.5.3 to 4.5.5.
I execute this command:
`helm upgrade --install nextcloud nextcloud/nextcloud --values nextcloud-values.yaml -n mynamespace --version 4.5.5`
I've also tried with version 4.5.4.
The readiness and liveness checks always fail. I can't see any relevant log record.
I use postgresql as external database and that is set in the values file (username and pw are in the values file too).
If I downgrade to version 4.5.3 everything works fine.

Has anybody the same problem? Am I missing something?

Thanks in advance for same clarification,

supermario18b

**Comment by provokateurin** [comment]
4.5.5 has a newer image version, so nextcloud performs an upgrade. You need to wait a bit for the upgrade to be done.
If the pods are killed during the upgrade you are running into https://github.com/nextcloud/helm/issues/333

**Comment by supermario18b** [comment]
@provokateurin thanks for your reply, you're right, I've set an higher value for `initialDelaySeconds` (livenessProbe und readinessProbe) and it worked.
