### ISSUE TITLE
Support additional pvc mounts

### ISSUE THREAD

**Issue by pfaelzerchen** [nextcloud/helm#500]
## Description of the change

My cluster has a couple of shared media pvcs that I want to mount into the Nextcloud container and then integrate as external storage. So I would need an option to specify additional volume mounts, e.g.

```yaml
additionalClaims:
  - claim: shared-media
    readOnly: false
  - claim: music
    readOnly: true
```

which mounts the claims under some common path, e.g. /data. With the current chart, I don't see the possibility to do this.

## Benefits

It will be possible to locally mount additional pvcs as external storage into Nextcloud.

## Possible drawbacks

It makes the chart more complex.

## Additional information

My use case is: The claims store a media library that is shared by different services (smb for SONOS, minidlnad, probably Jellyfin in the future), but that should also be integrated into Nextcloud (e.g. for music streaming from my mobile phone).

With the current setup, I have to deploy an additional service (e.g. an openSSH container) that exposes SFTP for integration. That should work in general, but I have to deal with additional user credentials.

Sorry, I cannot contribute a PR, but my abilities with helm aren't good enough. I'm still at the beginning.

**Comment by provokateurin** [comment]
This is already possible: https://github.com/nextcloud/helm/blob/99d643d99f22f14a033e297d89adfa6ccd628fe1/charts/nextcloud/values.yaml#L186. You only need to specify the volumes and the volume mounts and it should work :)

**Comment by pfaelzerchen** [comment]
How could I miss that? Thanks.
