### ISSUE TITLE
Cannot disable packaged PostgreSQL

### ISSUE THREAD

**Issue by vanthome** [nextcloud/helm#573]
## Describe your Issue

The [documentation says](https://github.com/nextcloud/helm/blob/main/charts/nextcloud/README.md#database-configurations) that:

>  You do not need to use the Bitnami helm charts. If you want to use an already configured database that you have externally, just set internalDatabase.enabled to false, and configure the externalDatabase parameters below.

This does not work, however. When I apply the chart, I still end up with a PostgreSQL instance although I have not deployed it separately.

**Comment by provokateurin** [comment]
Please show us your values.yaml

**Comment by vanthome** [comment]
Ignore, it was probably a glitch.
