### ISSUE TITLE
Request to update nextcloud app version to 20.0.x

### ISSUE THREAD

**Issue by iWangJiaxiang** [nextcloud/helm#61]
Is there an official update coming soon?

Or could I just modify the image tag when update nextcloud manually?

**Comment by agates** [comment]
I change the image tag and run helm upgrade without a problem. Currently running version 20.

(Remember to turn maintenance mode on before upgrade if you have users)

**Comment by varac** [comment]
Still it would be good to actually default to a newer version (right now latest helm chart install NC19, while NC21 is released already).

**Comment by varac** [comment]
(https://github.com/nextcloud/server/releases/tag/v21.0.0)
