### ISSUE TITLE
Nextcloud securityContext and rootlessness

### ISSUE THREAD

**Issue by BobyMCbobs** [nextcloud/helm#9]
# Goal
securityContext should be able to be configured in a values.yaml file.

With the configuration available, there should be default rules to secure the container to make it run as www-data instead of root (this may require running on a different port).

**Comment by tommyknows** [comment]
I don't have any experience running nextcloud (or php apps in general), but what would also be nice is to be able to set the user's ID. E.g. I want my nextcloud instance to run as user id `1234` (for example), which I'd set in the securityContext. This is useful if you have external storage - hostPaths that are mounted inside nextcloud.

**Comment by chrisingenhaag** [comment]
Hey, 
at the moment it isn´t so easy just to make securityContext configurable as we have to use specific fsGroup values for nginx and apache image. This is because nextcloud docker image copies files around during startup.

**Comment by BobyMCbobs** [comment]
I'm hoping to make sure that the Pods:
- are stateless (read only and have no moving parts aside from the data via PVCs)
- run as non-root

Would you suggest that I start with the [nextcloud/docker](https://github.com/nextcloud/docker) first?
