### ISSUE TITLE
Default php settings in container seem to be insufficient for maintenace:repair to run

### ISSUE THREAD

**Issue by Routhinator** [nextcloud/helm#97]
Just ran into this after a failed app update.

```
root@routhio-nextcloud-6d677d699f-wd7dn:/var/www/html# sudo -u www-data php occ maintenance:repair

Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 405504 bytes) in /var/www/html/3rdparty/composer/autoload_real.php on line 35
```

**Comment by tvories** [comment]
@Routhinator which chart version?

**Comment by Routhinator** [comment]
2.5.15. apparently it's a new bug with Nextcloud 20+

I managed to workaround it by passing:

```
-d memory_limit=-1
```

**Comment by Routhinator** [comment]
Oof, came back to running Nextcloud again after a couple of years and ended up back on my own issue haha. They should have used the numbering system for nextcloud.ini (IE `00-nextcloud.ini`) based on the override order. 

Testing this solution and will close this if it works.

**Comment by Routhinator** [comment]
This did work and solved the issue. Would be good to make this a part of the standard chart configs as the default 512M in the apache container is fairly small, however this works and is already exposed. Cheers @somerandow
